[Interface]
Address = 10.8.1.2/32
DNS = 1.1.1.1, 8.8.8.8
PrivateKey = UIMCVSKtYtnCfjNj0+vR3MN8wK8zSSnKH8qwal4TU3s=
Jc = 5
Jmin = 10
Jmax = 50
S1 = 12
S2 = 12
S3 = 12
S4 = 12
H1 = 1
H2 = 2
H3 = 3
H4 = 4
I1 = <r 2><b 0x858000010001000000000669636c6f756403636f6d0000010001c00c000100010000105a00044d583737>
HeaderProtectionKey = cKeYLnGqPLlFEnHkhi1JB9Flpu3F3fK03zycEowGNFc=
ContentPaddingAddition = 10-100
RekeyAfterTime = 100-120
RekeyTimeout = 3-7
RejectAfterTime = 150-180
KeepaliveTimeout = 5-15
MaxHandshakeAttempts = 15-20
RandomTrailers = on
DisableCookies = on

[Peer]
PublicKey = fBs7CTbEyH5ihIxOkVrL2TvknLdPnh2AWGD7tamLYSs=
PresharedKey = FrTH56jNtPmBxfIOdhzdW5sZ2rQkP8DI5oiPdUa/SYU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 77.110.114.5:443
PersistentKeepalive = 25
